# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: tunk
    env:
      - CGO_ENABLED=0
    main: ./cmd/tunk
    binary: tunk
    ldflags: -s -w -X github.com/jeffrom/tunk/release.Version={{.Version}} -X github.com/jeffrom/tunk/release.Commit={{.ShortCommit}} -X github.com/jeffrom/tunk/release.Date={{.Date}}

# dockers:
# - dockerfile: .goreleaser/Dockerfile
#   binaries:
#     - tunk
#   image_templates:
#   - "jeffrom/tunk:latest"
#   - "jeffrom/tunk:{{ .Major }}"
#   - "jeffrom/tunk:{{ .Major }}.{{ .Minor }}"
#   - "jeffrom/tunk:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
#   build_flag_templates:
#   - "--label=org.label-schema.schema-version=1.0"
#   - "--label=org.label-schema.version={{.Version}}"
#   - "--label=org.label-schema.name={{.ProjectName}}"
# - dockerfile: .goreleaser/Dockerfile.cli
#   binaries:
#     - tunk
#   image_templates:
#   - "jeffrom/tunk:latest"
#   - "jeffrom/tunk:{{ .Major }}"
#   - "jeffrom/tunk:{{ .Major }}.{{ .Minor }}"
#   - "jeffrom/tunk:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
#   build_flag_templates:
#   - "--label=org.label-schema.schema-version=1.0"
#   - "--label=org.label-schema.version={{.Version}}"
#   - "--label=org.label-schema.name={{.ProjectName}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - README.md
    - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
